### ISSUE TITLE
How to adapte 8Mbit flash with iot_firmware project?

### ISSUE THREAD

**Issue by Paulxia** [OLIMEX/ESP8266#35]
USER_CONFIG_START_SECTOR 0x07C
    flash_region_register("boot.bin",     0x000, 0x001);
    flash_region_register("user1.bin",    0x001, 0x07B);
    flash_region_register("user2.bin",    0x081, 0x07B);
    flash_region_register("user-config",  0x07C, 0x001);
    flash_region_register("PrivateKey",   0x07E, 0x001);
    flash_region_register("Certificate",  0x07F, 0x001);

**Comment by peter-valkov** [comment]
Looking at flash map for 1024KB (8Mbit) with FOTA support at the end of page 17 https://github.com/OLIMEX/ESP8266/blob/master/IoT%20Firmware/document/English/2A-ESP8266__IOT_SDK_User_Manual__EN_v1.5.pdf it looks like this should do the job. But I'm not able to test it because all our boards are equiped with 2048KB flash.
